### ISSUE TITLE
http-api-data-0.6 not accepted

### ISSUE THREAD

**Issue by ysangkok** [haskell-webgear/webgear#22]
This is preventing Stackage from upgrading:

* https://github.com/commercialhaskell/stackage/issues/7032

Constraint is from

https://github.com/haskell-webgear/webgear/blob/97aab9a28b307b1891ec4f7b4becad2a41bbf363/webgear-core/webgear-core.cabal#L60

**Comment by rkaippully** [comment]
Fixed in #17
