### ISSUE TITLE
network-3.2 not allowed

### ISSUE THREAD

**Issue by ysangkok** [haskell-webgear/webgear#49]
webgear-core requires `network ==3.1.*`, which means that network-3.2 isn't allowed. See:

* https://github.com/commercialhaskell/stackage/issues/7381

Note that Hackage maintainers can now [receive notifications when dependencies go out of bound](https://discourse.haskell.org/t/hackage-dep-bound-notifications-and-uploader-endorsements-for-new-users/8342?u=janus).

**Comment by ysangkok** [comment]
@rkaippully This should be easily fixable with a revision since `cabal repl -b webgear-core -c 'network>=3.2' -w ghc-9.6.5 --allow-newer=webgear-core:network` works with no issue.

**Comment by ysangkok** [comment]
@rkaippully If this were bumped, we'd be able to use the network version in Stackage Nightly

**Comment by rkaippully** [comment]
Fixed in #50

Bumped in 1.3.0-r1: https://hackage.haskell.org/package/webgear-core-1.3.0/revisions
